### ISSUE TITLE
LD file for fine-mapping-inf

### ISSUE THREAD

**Issue by snashraf** [FinucaneLab/fine-mapping-inf#10]
Dear Team,

I am trying to run the fine-mapping-inf. Thanks for the fantastic software. 

I have used the command below to generate LD files.

plink --bfile /gpfs/scratch/najeeb/VCFAfilesAnnotated/withKhalid/QGPMito/MutectUpdatedProcessing/associationAnalysis/fineMapping/regionwiseBedfile/${val} --keep-allele-order -r square --out ${name}

I have a few NaN values in my old files, which causes the fine map to fail while running.  
Would you happen to have any suggestions for generating the LD files?
Also, I have taken the following steps for analysis so far. Can you please confirm if it's correct?

1. I have taken the lead SNP from GWAS results after filtering 10 ^-8 ( Doesnt perform Clumping)
2.  For each lead SNP, take the 3 MB regions up and down.
3. Extract the statistics from the same region and calculate the LD for that region.
3. Run the Finemap analysis

Looking forward to your kind help.

**Comment by cuiran** [comment]
Hi,

We recommend using [LDstore v2.0](http://www.christianbenner.com/#) to generate the LD files. 

Your pipeline looks mostly correct. Do you mean filtering at the p-value threshold of 5 x 10^-8? For more detailed information regarding pipeline, we recommend using [this pipeline code](https://github.com/mkanai/finemapping-pipeline/tree/master). Specifically [make_finemap_inputs.py](python/make_finemap_inputs.py), [Dockerfile](docker/finemap-suite/Dockerfile), and [dsub_ldstore.py](dsub/dsub_ldstore.py) scripts may help with pre-processing your summary statistics and generating LD.

Let me know if you run into other problems.

**Comment by snashraf** [comment]
Thanks Alot  !!

yes, I meant filtering at 1 x 10 ^-8. I will try following above pipeline using LDstore and will let you know.

**Comment by snashraf** [comment]
Hi Cuiran,

I have a few NaN values in my old files, which causes the fine map to fail while running.
Now I could run with LDstore, and I still have NaN values. 
Can I convert these values to 0 or some other values?

**Comment by snashraf** [comment]
Hi Cuiran,

Sorry for asking again. But unfortunately I have been struggling this with long time for a very tight deadlines.

Do you have any suggestions for above request?

Thanks again!!
Regards
Najeeb

**Comment by cuiran** [comment]
Hi Najeeb,

My first guess is that the NaN values may be the result of missing genotype values? I'd recommend first trying to filter out the individuals with too much missingness. If that doesn't work for some reason, and if there are not too many NaNs in your LD file, you can remove those the SNPs with missing LD values from your initial analysis. Just be aware of this filtering process when you are interpreting the results. Because if you remove SNPs, you may be removing causal SNPs.

**Comment by snashraf** [comment]
I replaced the missing genotype with the homozygous reference and am still encountering the same issue.

**Comment by cuiran** [comment]
Can you post the error log?

**Comment by snashraf** [comment]
Sorry for the late posting due to time difference. 

Traceback (most recent call last):
  File "/gpfs/software/genomics/FinucaneLab/fine-mapping-inf/fine-mapping-inf_v1.0/run_fine_mapping.py", line 183, in <module>
    eigenvals,V = scipy.linalg.eigh(LD, lower=(not args.upper_triangular_ld_matrix))
  File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/scipy/linalg/_decomp.py", line 447, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/scipy/_lib/_util.py", line 287, in _asarray_validated
    a = toarray(a)
  File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs

**Comment by cuiran** [comment]
Looks like it’s a file extension issue. Please see Wiki for input file format guidelines. In particular, ld file : “This file can be a text file with compression .gz or .bgz, or in .npy or .npz format.”

**Comment by snashraf** [comment]
Hi Cuiran,

I have updated the error log above. Please check. I have corrected the file extension issue.  Correct error log is below.

Traceback (most recent call last):
File "/gpfs/software/genomics/FinucaneLab/fine-mapping-inf/fine-mapping-inf_v1.0/run_fine_mapping.py", line 183, in
eigenvals,V = scipy.linalg.eigh(LD, lower=(not args.upper_triangular_ld_matrix))
File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/scipy/linalg/_decomp.py", line 447, in eigh
a1 = _asarray_validated(a, check_finite=check_finite)
File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/scipy/_lib/_util.py", line 287, in _asarray_validated
a = toarray(a)
File "/gpfs/software/tools/python-3.9.12/Python-3.9.12/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
raise ValueError(
ValueError: array must not contain infs or NaNs

**Comment by cuiran** [comment]
Does your LDstore log seems normal? You can read in your LD file (if it's too big, you can try reading in the first half) and see where the NaNs or infs are occuring? You can also plot a LD heatmap and see if your LD block structure looks like what you would expect.

**Comment by snashraf** [comment]
Hi Cuiran,

I solved the NaN issue. This was coming due to the variants with AF as .50 . Now I am stuck with the next step. I am using the below command

python3.9 /gpfs/software/genomics/FinucaneLab/fine-mapping-inf/fine-mapping-inf_v1.0/run_fine_mapping.py --sumstats extractedRegion_2_88423618_inversenorm_withoutNAN.sumstat --beta-col-name beta --se-col-name se --ld-file extractedRegion_2_88423618.ld.gz --n 14000 --save-npz --save-tsv --eigen-decomp-prefix chr2_97150376 --output-prefix MT_CN.chr2_97150376

And getting the core dumped at the eigen decomposition step. I am using a fairly large machine. I have 149154 variants in my file. Would you happen to know if I can't use this many variants for the fine mapping? Do you have any other suggestions for me?
Thanks for your suggestions and help.

**Comment by cuiran** [comment]
That's a lot of variants! The median number of variants in our fine-mapping regions is about 16K. How did you define mapping regions? Did you use the preprocessing pipeline in [make_finemap_inputs.py](https://github.com/FinucaneLab/fine-mapping-inf/issues/python/make_finemap_inputs.py)? If you are, given your sample size of 14K, I'd be very surprised if you have a region with a lot more than 20K variants. Unless maybe you have sequencing data?

**Comment by snashraf** [comment]
Its WGS data and I have taken 3 MB region. What's the recommendation for that?

I am not sure how they managed to do it in this paper. https://www.nature.com/articles/s41586-023-06426-5
Do you have an AF cutoff recommendation also?

**Comment by cuiran** [comment]
The mtSwirl paper defined their phenotypes with WGS data, but the fine-mapped SNPs were UKB array data. If you need to use WGS genotypes to finemap, you can try using 1Mb windows instead of 3Mb. For QC protocol, see [Kanai et. al. 2021 medRxiv](https://www.medrxiv.org/content/10.1101/2021.09.03.21262975v1)
