### ISSUE TITLE
Credible sets for Finemap-inf

### ISSUE THREAD

**Issue by sayangsep** [FinucaneLab/fine-mapping-inf#3]
Hi,
I was trying to run Finemap-inf and generate credible sets. But, I cannot find the outputs for credible sets. Could you please guide me on this?

**Comment by cuiran** [comment]
Hi, we currently only have credible set information for SuSiE-inf not FINEMAP-inf. If you run the run_fine_mapping.py script, The SuSiE-inf credible set information can be found in the column named ‘cs’. The different numerical values indicate which credible set the corresponding SNP is in, -1 value means the SNP is not in any credible set. If you run susieinf.py directly, the credible set information is stored in the key ‘cred’ in the outputted dictionary. Let me know if that helps.

**Comment by sayangsep** [comment]
Thank you for your reply! I have another question: 
While running susie-inf is there a way to fix $s^2$ (i.e. variance of fixed effects) and $\tau^2$ (variance of residual noise)?

**Comment by cuiran** [comment]
Yes, you can specify `ssq` and `tausq` in the function `susie` in `susieinf.py`
https://github.com/FinucaneLab/fine-mapping-inf/blob/4af3e6ebf04f372bcb641977601a2b65a4080237/susieinf/susieinf.py#L79

**Comment by sayangsep** [comment]
Thanks for your reply! While running susie-inf I am encountering the following error. Can you please tell me what's causing this error? I am also attaching my z-file and LD file for your reference.


##################
Error
##################
Reading summary statistics from file /mnt/sdb1/sayan/finemapping_mixed/data/data21/setting60/Simulation_data1.z
         0          1
0      rs0 -13.799580
1      rs1  16.040077
2      rs2  -8.640558
3      rs3   4.779611
4      rs4  36.948448
..     ...        ...
995  rs995  -7.753660
996  rs996   1.300606
997  rs997  -7.236649
998  rs998  -2.895833
999  rs999   1.436788

[1000 rows x 2 columns]
1000 SNPs in summary statistics file
Reading in LD matrix from file /mnt/sdb1/sayan/finemapping_mixed/data/data21/setting60/Simulation_data1.ld
Reading in LD matrix took 0.12 seconds
Performing eigen decomposition
Eigen decomposition took 0.18 seconds
Running susieinf
*********************************************************************
* SuSiE-inf
* Version 1.2
* (C) Zhou Fan
*********************************************************************
/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py:170: RuntimeWarning: invalid value encountered in log
  return -scipy.special.logsumexp(-0.5*np.log(1+x*diagXtOmegaX ) \
/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py:181: RuntimeWarning: invalid value encountered in log
  logPIP = XtOmegar**2/(2*omega[:,l])-0.5*np.log(omega[:,l]*ssq[l] )+logpi0
Iteration 0
Update s^2 for effect 0 to 0.999995
Update s^2 for effect 1 to 0.023139
Update s^2 for effect 2 to 0.008940
Update s^2 for effect 3 to 0.014246
Update s^2 for effect 4 to 0.013241
Update s^2 for effect 5 to 0.004850
Update s^2 for effect 6 to 0.007866
Update s^2 for effect 7 to 0.002449
Update s^2 for effect 8 to 0.003442
Update s^2 for effect 9 to 0.002888
Update s^2 for effect 10 to 0.000793
Update s^2 for effect 11 to 0.000363
Update s^2 for effect 12 to 0.000238
Update s^2 for effect 13 to 0.000150
Update s^2 for effect 14 to 0.000077
Update s^2 for effect 15 to 0.000026
Update s^2 for effect 16 to 0.000008
Update s^2 for effect 17 to 0.000006
Update s^2 for effect 18 to 0.000006
Update s^2 for effect 19 to 0.000006
Update (sigma^2,tau^2) to (-0.113639,0.000000e+00)
Maximum change in PIP: 0.999000
Iteration 1
WARNING: s^2 update for iteration 1, effect 0 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 1 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 2 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 3 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 4 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 5 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 6 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 7 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 8 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 9 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 10 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 11 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 12 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 13 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 14 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 15 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 16 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 17 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 18 failed to converge; keeping previous parameters
WARNING: s^2 update for iteration 1, effect 19 failed to converge; keeping previous parameters
Traceback (most recent call last):
  File "/home/sayan/hdd/sayan/finemapping_mixed/plos_experiments/susie_inf/run_fine_mapping.py", line 199, in <module>
    susie_output = susie(z, args.meansq, args.n, args.num_sparse_effects, LD=None, V=V, Dsq=Dsq,
  File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py", line 186, in susie
    (sigmasq,tausq) = MoM(PIP,mu,omega,sigmasq,tausq,n,V,Dsq,VtXty,Xty,yty,
  File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py", line 29, in MoM
    sol = scipy.linalg.solve(A,x)
  File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 144, in solve
    b1 = atleast_1d(_asarray_validated(b, check_finite=check_finite))
  File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/scipy/_lib/_util.py", line 252, in _asarray_validated
    a = toarray(a)
  File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/numpy/lib/function_base.py", line 628, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
[Simulation_data.zip](https://github.com/FinucaneLab/fine-mapping-inf/files/11583038/Simulation_data.zip)

**Comment by wuyangf7** [comment]
Hi Ran, I have a related question about whether susie-inf has a flag to input a parameter (e.g., 0.95) for coverage of the credible set?

**Comment by diyan971012** [comment]
> Thanks for your reply! While running susie-inf I am encountering the following error. Can you please tell me what's causing this error? I am also attaching my z-file and LD file for your reference.
> 
> ################## Error ################## Reading summary statistics from file /mnt/sdb1/sayan/finemapping_mixed/data/data21/setting60/Simulation_data1.z 0 1 0 rs0 -13.799580 1 rs1 16.040077 2 rs2 -8.640558 3 rs3 4.779611 4 rs4 36.948448 .. ... ... 995 rs995 -7.753660 996 rs996 1.300606 997 rs997 -7.236649 998 rs998 -2.895833 999 rs999 1.436788
> 
> [1000 rows x 2 columns] 1000 SNPs in summary statistics file Reading in LD matrix from file /mnt/sdb1/sayan/finemapping_mixed/data/data21/setting60/Simulation_data1.ld Reading in LD matrix took 0.12 seconds Performing eigen decomposition Eigen decomposition took 0.18 seconds Running susieinf
> 
> * SuSiE-inf
> * Version 1.2
> * (C) Zhou Fan
> 
> /home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py:170: RuntimeWarning: invalid value encountered in log return -scipy.special.logsumexp(-0.5_np.log(1+x_diagXtOmegaX ) /home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py:181: RuntimeWarning: invalid value encountered in log logPIP = XtOmegar**2/(2_omega[:,l])-0.5_np.log(omega[:,l]*ssq[l] )+logpi0 Iteration 0 Update s^2 for effect 0 to 0.999995 Update s^2 for effect 1 to 0.023139 Update s^2 for effect 2 to 0.008940 Update s^2 for effect 3 to 0.014246 Update s^2 for effect 4 to 0.013241 Update s^2 for effect 5 to 0.004850 Update s^2 for effect 6 to 0.007866 Update s^2 for effect 7 to 0.002449 Update s^2 for effect 8 to 0.003442 Update s^2 for effect 9 to 0.002888 Update s^2 for effect 10 to 0.000793 Update s^2 for effect 11 to 0.000363 Update s^2 for effect 12 to 0.000238 Update s^2 for effect 13 to 0.000150 Update s^2 for effect 14 to 0.000077 Update s^2 for effect 15 to 0.000026 Update s^2 for effect 16 to 0.000008 Update s^2 for effect 17 to 0.000006 Update s^2 for effect 18 to 0.000006 Update s^2 for effect 19 to 0.000006 Update (sigma^2,tau^2) to (-0.113639,0.000000e+00) Maximum change in PIP: 0.999000 Iteration 1 WARNING: s^2 update for iteration 1, effect 0 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 1 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 2 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 3 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 4 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 5 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 6 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 7 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 8 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 9 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 10 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 11 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 12 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 13 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 14 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 15 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 16 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 17 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 18 failed to converge; keeping previous parameters WARNING: s^2 update for iteration 1, effect 19 failed to converge; keeping previous parameters Traceback (most recent call last): File "/home/sayan/hdd/sayan/finemapping_mixed/plos_experiments/susie_inf/run_fine_mapping.py", line 199, in susie_output = susie(z, args.meansq, args.n, args.num_sparse_effects, LD=None, V=V, Dsq=Dsq, File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py", line 186, in susie (sigmasq,tausq) = MoM(PIP,mu,omega,sigmasq,tausq,n,V,Dsq,VtXty,Xty,yty, File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/susieinf.py", line 29, in MoM sol = scipy.linalg.solve(A,x) File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 144, in solve b1 = atleast_1d(_asarray_validated(b, check_finite=check_finite)) File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/scipy/_lib/_util.py", line 252, in _asarray_validated a = toarray(a) File "/home/sayan/anaconda3/envs/finemapping_inf/lib/python3.9/site-packages/numpy/lib/function_base.py", line 628, in asarray_chkfinite raise ValueError( ValueError: array must not contain infs or NaNs [Simulation_data.zip](https://github.com/FinucaneLab/fine-mapping-inf/files/11583038/Simulation_data.zip)

I have the same error,have you find the reason? Can you please tell me?

**Comment by sayangsep** [comment]
Unfortunately no. I ended up using other tools. 

1. Finemap: http://www.christianbenner.com/
2. Finamp-inf
3. CARMA: https://github.com/ZikunY/CARMA
4. BEATRICE: https://github.com/sayangsep/Beatrice-Finemapping/tree/main
